### ISSUE TITLE
Status responses in Espurna 15.x

### ISSUE THREAD

**Issue by swilson86** [mcspr/espurna-nightly-builder#11] opened 2022-02-07 23:20 UTC
Espurna 1.14.1 and nightly build 1.15.x (nightly20220116) have a significant difference that will break a lot of existing code (in my case within node-red). Release 1.14.1 puts out floats and ints in the payload, 1.15.x puts out strings or char arrays. That means a ton of code changes in node-red functions to check and convert the strings to float/int. On a Raspberry Pi that is more memory used. Solution... keep the output consistent between versions (and it would be nice to keep them in the same order too). Here is a printout from a microwave V1.14.1 and a coffee maker V1.15.x:

topic: "Microwave/data"
payload: object
current: 0
voltage: 118
power: 0
reactive: 0
apparent: 0
factor: 100
energy: 0.276
time: "2022-02-07 18:01:43"
mac: "CC:50:E3:1B:B9:00"
host: "Microwave"
ip: "192.168.68.102"
id: 5212
qos: 0
retain: false

topic: "Coffee/data"
payload: object
datetime: "2022-02-07 18:01:59"
mac: "5C:CF:7F:7D:2A:F1"
host: "Coffee"
ip: "192.168.68.52"
id: 1995
energy: "0.250"
factor: "0"
apparent: "0"
reactive: "0"
power: "0"
voltage: "124"
current: "0.000"
qos: 0
retain: false

**Comment by mcspr** [comment] 2022-02-08 11:34
Duplicate of xoseperez/espurna#2503
(pls use that tracker in the future)

>  On a Raspberry Pi that is more memory used

...I'd highly doubt that though :) I agree that this is a breaking change though, it should be fixed.
But, code *could* just use [`parseFloat()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat), it is a pretty standard JS stuff and is a noop if the argument is already floating point.

**Closed as completed by mcspr** 2022-02-08 11:34 UTC
